name: Release

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/Checkout@v4
      - name: Release
        uses: dagger/dagger-for-github@v8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
          GPG_KEY_ID: ${{ vars.GPG_KEY_ID }}
        with:
          version: "latest"
          verb: call 
          module: gopkg 
          args: |
            with-git-gpg-config \
              --gpg-key=env://GPG_KEY \
              --gpg-key-id=env://GPG_KEY_ID \
              --git-author-name "semantic-release-bot" \
              --git-author-email "shukomango@gmail.com" \
            release \
              --source=. \
              --dry-run=false \
              --token=env://GITHUB_TOKEN
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

